# do not commit this to a public repo!

production: &PROD
  :site_name: Resource Tracker
  :site_description: Health Resource Tracking & Planning
  :admin_pass: password

staging:
   <<: *PROD

test:
  <<: *PROD
  :autofeature: 'true'
  :rspec: 'true'

cucumber:
  <<: *PROD
  :autofeature: 'true'
  :rspec: 'true'

development:
  <<: *PROD